name: Build Installer
run-name: ${{ github.workflow }} ${{ github.event.repository.updated_at}}

on:
  workflow_call:
    outputs:
      artifact_id:
        description: "The ID of the generated artifact"
        value: ${{ jobs.build-installer.outputs.artifact_id }}
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "00 00 * * 5"

permissions:
  contents: read

jobs:
  build-installer:
    name: Build Installer
    runs-on: windows-latest
    outputs:
      artifact_name: ${{ steps.get-installer-name.outputs.artifact_name }}
      artifact_path: ${{ steps.get-installer-name.outputs.artifact_path }}

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "clippy, rustfmt"

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Run Clippy
        run: cargo clippy --release -- -D warnings

      - name: Run rustfmt check
        run: cargo check --release

      - name: Build Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build/setup/setup.iss

      - name: Get Installer Name
        id: get-installer-name
        run: |
          $installerName = $(ls .\build\setup\Output\*.exe).BaseName
          $installerPath = $(ls .\build\setup\Output\*.exe).FullName

          echo "artifact_name=$installerName" >> $env:GITHUB_OUTPUT
          echo "artifact_path=$installerPath" >> $env:GITHUB_OUTPUT

      - name: Create Artifact ${{ steps.get-installer-name.outputs.artifact_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-installer-name.outputs.artifact_name }}
          path: ${{ steps.get-installer-name.outputs.artifact_path }}
          if-no-files-found: error
